package nodedep

import (
	"fmt"
	"path"
	"sort"
	"strings"
	"time"

	"github.com/winger/ai-gateway/internal/dshgw/nodestore"
)

// GenerateNodeConfig renders the worker node's configuration (M77).
//
// It is generated on the control plane for one reason: the deploy knows both sides. The node's own
// identity (name, listen, token file) and its machine-local paths come from the record; the
// tenant-side behaviour (picker, plugins, ssh/browser workspaces, host shares, worker limits) comes
// from the control plane's configuration, because a tenant that behaves differently depending on
// which node it landed on would be a bug nobody could reproduce.
//
// The file is strict-decoded by the node, so every key written here is one `config.Load` accepts;
// the generator is covered by a test that loads its output.
func GenerateNodeConfig(target nodestore.Node, opts Options, token string, keepToken bool) ([]byte, error) {
	layout := newLayout(target)
	bwrap, nodeBin, binJS, currentLink := runtimePaths(target, opts)
	if strings.TrimSpace(nodeBin) == "" || strings.TrimSpace(binJS) == "" {
		return nil, fmt.Errorf("node %s: the Node runtime and the dsh launcher must be named (dsh.node_bin / dsh.bin_js)", target.Name)
	}
	picker := strings.TrimSpace(opts.DirectoryPicker)
	if picker == "" {
		picker = "clamp"
	}
	browserFS := strings.TrimSpace(opts.PluginBrowserFS)
	if browserFS == "" {
		browserFS = "on"
	}
	workerLo, workerHi := target.Deploy.WorkerPortLo, target.Deploy.WorkerPortHi
	if workerLo == 0 {
		workerLo = 32800
	}
	if workerHi == 0 {
		workerHi = 32899
	}

	var b strings.Builder
	b.WriteString("# Generated by `dshgw node deploy` (M77) — do not edit by hand.\n")
	b.WriteString("# The control plane owns this file: the next deploy replaces it.\n")
	fmt.Fprintf(&b, "state_dir: %s\n", layout.stateDir)
	fmt.Fprintf(&b, "tenant_root: %s\n", path.Join(layout.stateDir, "tenants"))
	fmt.Fprintf(&b, "workspace_root: %s\n", path.Join(layout.stateDir, "workspaces"))
	fmt.Fprintf(&b, "handshake_dir: %s\n", path.Join(layout.stateDir, "handshake"))
	fmt.Fprintf(&b, "registry_path: %s\n", path.Join(layout.stateDir, "registry.json"))
	fmt.Fprintf(&b, "key_map_path: %s\n", path.Join(layout.stateDir, "keys.map"))
	fmt.Fprintf(&b, "audit_path: %s\n", path.Join(layout.stateDir, "gateway", "audit.jsonl"))
	fmt.Fprintf(&b, "worker_port_lo: %d\n", workerLo)
	fmt.Fprintf(&b, "worker_port_hi: %d\n", workerHi)
	fmt.Fprintf(&b, "aigw_base_url: %s\n", strings.TrimSpace(opts.AigwBaseURL))
	fmt.Fprintf(&b, "directory_picker: %s\n", picker)
	fmt.Fprintf(&b, "plugin_browser_fs: %s\n", browserFS)
	b.WriteString("workspace_seed: [work]\n")
	b.WriteString("\nnode:\n")
	fmt.Fprintf(&b, "  name: %s\n", target.Name)
	fmt.Fprintf(&b, "  listen: %s\n", strings.TrimSpace(target.Listen))
	if keepToken {
		// The token file is already on the target: naming it is enough, and the deploy leaves the
		// value alone (a token that changes on every deploy would break the control plane's record).
		fmt.Fprintf(&b, "  token_file: %s\n", layout.tokenPath)
	} else {
		fmt.Fprintf(&b, "  token_file: %s\n", layout.tokenPath)
	}
	b.WriteString("\ndeploy:\n")
	fmt.Fprintf(&b, "  plugin_path: %s\n", path.Join(layout.pluginDir, "picker-clamp.js"))
	fmt.Fprintf(&b, "  template_home: %s\n", layout.templateHome)
	fmt.Fprintf(&b, "  bwrap_bin: %s\n", bwrap)
	fmt.Fprintf(&b, "  backup_dir: %s\n", path.Join(layout.stateDir, "backups"))
	fmt.Fprintf(&b, "  config_path: %s\n", layout.configPath)
	b.WriteString("\ndsh:\n")
	fmt.Fprintf(&b, "  node_bin: %s\n", nodeBin)
	fmt.Fprintf(&b, "  bin_js: %s\n", binJS)
	if currentLink != "" {
		fmt.Fprintf(&b, "  current_link: %s\n", currentLink)
	}
	if limits := opts.WorkerLimits; limits.MemoryHighBytes > 0 || limits.MemoryMaxBytes > 0 || limits.TasksMax > 0 || limits.CPUQuotaPercent > 0 {
		b.WriteString("\nworker_limits:\n")
		fmt.Fprintf(&b, "  memory_high_bytes: %d\n", limits.MemoryHighBytes)
		fmt.Fprintf(&b, "  memory_max_bytes: %d\n", limits.MemoryMaxBytes)
		fmt.Fprintf(&b, "  tasks_max: %d\n", limits.TasksMax)
		fmt.Fprintf(&b, "  cpu_quota_percent: %d\n", limits.CPUQuotaPercent)
	}
	b.WriteString("\ntenant_plugins:\n")
	fmt.Fprintf(&b, "  web_tty: {enabled: %t}\n", opts.TenantPlugins.WebTTY.Enabled)
	fmt.Fprintf(&b, "  workspace_files: {enabled: %t}\n", opts.TenantPlugins.WorkspaceFiles.Enabled)
	fmt.Fprintf(&b, "  git_diff: {enabled: %t}\n", opts.TenantPlugins.GitDiff.Enabled)
	if strings.TrimSpace(opts.TenantPlugins.RootLabel) != "" {
		fmt.Fprintf(&b, "  root_label: %s\n", opts.TenantPlugins.RootLabel)
	}
	b.WriteString("\nssh_workspaces:\n")
	fmt.Fprintf(&b, "  enabled: %t\n", opts.SSHWorkspaces)
	b.WriteString("\nbrowser_workspaces:\n")
	fmt.Fprintf(&b, "  enabled: %t\n", opts.BrowserWorkspaces)
	if shares := opts.HostShares; shares != nil && shares.Enabled && len(shares.Shares) > 0 {
		b.WriteString("\nhost_shares:\n")
		b.WriteString("  enabled: true\n")
		subdir := shares.Subdir
		if subdir == "" {
			subdir = "host"
		}
		fmt.Fprintf(&b, "  subdir: %s\n", subdir)
		b.WriteString("  shares:\n")
		for _, share := range shares.Shares {
			fmt.Fprintf(&b, "    - name: %s\n", share.Name)
			fmt.Fprintf(&b, "      path: %s\n", share.Path)
			fmt.Fprintf(&b, "      read_only: %t\n", share.EffectiveReadOnly())
			tenants := append([]string(nil), share.Tenants...)
			sort.Strings(tenants)
			fmt.Fprintf(&b, "      tenants: [%s]\n", strings.Join(tenants, ", "))
		}
	}
	return []byte(b.String()), nil
}

// GenerateUnit renders the systemd user unit that supervises the node.
//
// It is a *user* unit because this deployment has no root: the same shape the gateway itself runs
// under (M58). Restart=always is what makes a node come back after its process dies, and
// WorkingDirectory is the deployment directory so relative configuration paths keep meaning the
// same thing.
func GenerateUnit(target nodestore.Node, l layout) []byte {
	var b strings.Builder
	b.WriteString("# Generated by `dshgw node deploy` (M77) — do not edit by hand.\n")
	b.WriteString("[Unit]\n")
	fmt.Fprintf(&b, "Description=dshgw worker node %s\n", target.Name)
	b.WriteString("After=default.target\n\n")
	b.WriteString("[Service]\n")
	fmt.Fprintf(&b, "WorkingDirectory=%s\n", l.dir)
	fmt.Fprintf(&b, "ExecStart=%s --config %s node serve\n", path.Join(l.binDir, "dshgw"), l.configPath)
	b.WriteString("Restart=always\nRestartSec=2\n")
	fmt.Fprintf(&b, "StandardOutput=append:%s\n", l.logFile)
	fmt.Fprintf(&b, "StandardError=append:%s\n", l.logFile)
	b.WriteString("\n[Install]\nWantedBy=default.target\n")
	return []byte(b.String())
}

// RecordFromResult folds a deploy's outcome into the node record the control plane stores: the
// token (or the confirmation that the old one still stands), the fingerprint that was pinned and
// the paths the deploy used.
func RecordFromResult(record nodestore.Node, result Result, opts Options, assets Assets) nodestore.Node {
	layout := newLayout(record)
	if result.Token != "" {
		// Either this deploy rotated the token or the caller supplied one; in both cases the record
		// must carry the value the node now has. A deploy that kept the target's existing token
		// reports no token, and the record keeps what it had.
		record.Token = result.Token
	}
	record.TokenFile = ""
	record.Deploy.TokenPath = layout.tokenPath
	record.Deploy.Dir = layout.dir
	record.Deploy.StateDir = layout.stateDir
	record.Deploy.PluginPath = path.Join(layout.pluginDir, "picker-clamp.js")
	record.Deploy.TemplateHome = layout.templateHome
	if result.Fingerprint != "" {
		record.SSH.HostKeyFingerprint = result.Fingerprint
	}
	record.Status.State = nodestore.StateReady
	record.Status.Phase = ""
	record.Status.Error = ""
	record.Status.Version = result.Version
	record.Status.Revision = result.Revision
	record.Status.Protocol = 1
	record.Status.FinishedAt = timeNow()
	record.Status.ReadyAt = record.Status.FinishedAt
	record.Status.Reachable = true
	record.Status.ProbedAt = record.Status.FinishedAt
	return record
}

// NodeConfigSummary is a one-line description of a generated configuration, for the deploy log.
func NodeConfigSummary(data []byte) string {
	var listen, state string
	for _, line := range strings.Split(string(data), "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "listen:") {
			listen = strings.TrimSpace(strings.TrimPrefix(trimmed, "listen:"))
		}
		if strings.HasPrefix(trimmed, "state_dir:") {
			state = strings.TrimSpace(strings.TrimPrefix(trimmed, "state_dir:"))
		}
	}
	return fmt.Sprintf("listen=%s state_dir=%s bytes=%d", listen, state, len(data))
}

// TimeNow is injectable for tests that assert the recorded timestamps.
var TimeNow = func() time.Time { return time.Now().UTC() }

func timeNow() time.Time { return TimeNow() }
