// Builds client.js from the vendored UMD bundles plus client.src.js.
//
// Why a build step at all: this installation ships no bundler, and dsh serves a client plugin's
// ./client file byte for byte as a same-origin classic script. The two vendor files are UMD
// builds that assign their exports onto globalThis when no CommonJS/AMD loader is present, so
// concatenating them ahead of this plugin's own source is the whole bundling story.
//
// Run: node build-client.mjs   (writes ./client.js)

import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const read = (name) => readFileSync(join(here, name), 'utf8')
const digest = (text) => createHash('sha256').update(text).digest('hex').slice(0, 16)

/** Drop the trailing sourceMappingURL comment: the .map files are not shipped. */
const withoutSourceMap = (text) => text.replace(/\n?\/\/# sourceMappingURL=[^\n]*\n?$/, '\n')

const xterm = withoutSourceMap(read('vendor/xterm.js'))
const fit = withoutSourceMap(read('vendor/addon-fit.js'))
const css = read('vendor/xterm.css')
const source = read('client.src.js')

/**
 * Wrap one UMD bundle so its CommonJS/AMD branches cannot fire.
 *
 * The served file is a classic script, but the shell's loader is free to hand it a `module`,
 * `exports` or `define` binding in the future; shadowing all three here forces the UMD wrapper
 * down its globalThis branch, which is the one this plugin's source reads from.
 */
const wrap = (name, text) => `;(function () { var module, exports, define;\n/* ${name} */\n${text}\n})();\n`

const header = [
  '/* dshgw-web-tty — generated by build-client.mjs; edit client.src.js, not this file.',
  ` * xterm.js 6.0.0 (MIT)                 sha256:${digest(xterm)}`,
  ` * @xterm/addon-fit 0.11.0 (MIT)        sha256:${digest(fit)}`,
  ` * xterm.css                            sha256:${digest(css)}`,
  ` * client.src.js                        sha256:${digest(source)}`,
  ' */',
  '',
].join('\n')

const output = [
  header,
  wrap('xterm.js 6.0.0', xterm),
  wrap('@xterm/addon-fit 0.11.0', fit),
  `window.__DSHGW_WEB_TTY_XTERM_CSS__ = ${JSON.stringify(css)};`,
  '',
  source,
].join('\n')

writeFileSync(join(here, 'client.js'), output)
const bytes = Buffer.byteLength(output)
process.stdout.write(`client.js written: ${bytes} bytes (${(bytes / 1024).toFixed(1)} KiB)\n`)
