package sshworkspace

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The alias list an account starts with comes from <ssh_config_dir>/<account> and from
// nothing else. These tests pin the three properties that make that true: the seed is read
// per account, a missing seed is an empty list rather than a fallback, and a seed that is
// not a plain private file is refused instead of quietly skipped.

// writeSeed creates <dir>/<account> and returns the directory. The mode is forced after the
// write: a plain WriteFile is masked by the umask, which would silently weaken a test that
// depends on an exact mode.
func writeSeed(t *testing.T, account, content string, mode os.FileMode) string {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, account)
	if err := os.WriteFile(path, []byte(content), mode); err != nil {
		t.Fatalf("writing the seed: %v", err)
	}
	if err := os.Chmod(path, mode); err != nil {
		t.Fatalf("setting the seed mode: %v", err)
	}
	return dir
}

func workspaceConfig(t *testing.T, workspace string) string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(workspace, ".ssh", "config"))
	if err != nil {
		t.Fatalf("reading the provisioned config: %v", err)
	}
	return string(data)
}

// secondRemote is another account's roots inside the same fixture.
func secondRemote(env *testEnv, tenant string) Remote {
	return Remote{
		Tenant:    tenant,
		Workspace: filepath.Join(env.root, "state", "workspaces", tenant),
		DshHome:   filepath.Join(env.root, "state", "tenants", tenant, ".dsh"),
	}
}

func TestSeedConfigIsReadPerAccount(t *testing.T) {
	dir := writeSeed(t, "dsh-colin", "Host colin-only\n  HostName 10.0.0.1\n", 0o644)
	if err := os.WriteFile(filepath.Join(dir, "dsh-ran"), []byte("Host ran-only\n  HostName 10.0.0.2\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	env := newTestEnv(t, Options{SSHConfigDir: dir})

	if got := workspaceConfig(t, env.remote.Workspace); !strings.Contains(got, "Host colin-only") {
		t.Errorf("the account did not get its own seed:\n%s", got)
	} else if strings.Contains(got, "ran-only") {
		t.Errorf("the account got another account's seed:\n%s", got)
	}

	other := secondRemote(env, "dsh-ran")
	if err := os.MkdirAll(other.DshHome, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := env.service.EnsureIdentity(other.Tenant, other.Workspace, other.DshHome); err != nil {
		t.Fatalf("EnsureIdentity for the second account: %v", err)
	}
	if got := workspaceConfig(t, other.Workspace); !strings.Contains(got, "Host ran-only") {
		t.Errorf("the second account did not get its own seed:\n%s", got)
	} else if strings.Contains(got, "colin-only") {
		t.Errorf("the second account got another account's seed:\n%s", got)
	}
}

func TestSeedConfigMissingLeavesAnEmptyAliasList(t *testing.T) {
	env := newTestEnv(t, Options{SSHConfigDir: t.TempDir()})
	got := workspaceConfig(t, env.remote.Workspace)
	if !strings.Contains(got, "Generated by dshgw") {
		t.Errorf("an account with no seed still gets the account-owned config:\n%s", got)
	}
	if strings.Contains(got, "Host ") {
		t.Errorf("an account with no seed must start with no aliases:\n%s", got)
	}
}

// A seed is the operator's statement about which hosts the account may reach; one that cannot
// be read as written is an error, never a silent "start with nothing".
func TestSeedConfigRefusesUnusableFiles(t *testing.T) {
	plain := "Host aipc\n  HostName 10.0.0.9\n"
	t.Run("world writable", func(t *testing.T) {
		dir := writeSeed(t, "dsh-colin", plain, 0o666)
		env := newTestEnv(t, Options{SSHConfigDir: dir})
		if err := env.service.EnsureIdentity("dsh-colin", env.remote.Workspace, env.remote.DshHome); err == nil {
			t.Fatal("a world-writable seed was accepted")
		} else if CodeOf(err) != CodeInvalidState {
			t.Fatalf("the refusal is not the seed check: %v", err)
		}
	})
	t.Run("symlink", func(t *testing.T) {
		dir := t.TempDir()
		target := filepath.Join(t.TempDir(), "real-config")
		if err := os.WriteFile(target, []byte(plain), 0o644); err != nil {
			t.Fatal(err)
		}
		if err := os.Symlink(target, filepath.Join(dir, "dsh-colin")); err != nil {
			t.Fatal(err)
		}
		env := newTestEnv(t, Options{SSHConfigDir: dir})
		if err := env.service.EnsureIdentity("dsh-colin", env.remote.Workspace, env.remote.DshHome); err == nil {
			t.Fatal("a symlinked seed was accepted")
		}
	})
	t.Run("hard linked", func(t *testing.T) {
		dir := writeSeed(t, "dsh-colin", plain, 0o644)
		if err := os.Link(filepath.Join(dir, "dsh-colin"), filepath.Join(dir, "elsewhere")); err != nil {
			t.Fatal(err)
		}
		env := newTestEnv(t, Options{SSHConfigDir: dir})
		if err := env.service.EnsureIdentity("dsh-colin", env.remote.Workspace, env.remote.DshHome); err == nil {
			t.Fatal("a hard-linked seed was accepted")
		}
	})
	t.Run("directory", func(t *testing.T) {
		dir := t.TempDir()
		if err := os.Mkdir(filepath.Join(dir, "dsh-colin"), 0o700); err != nil {
			t.Fatal(err)
		}
		env := newTestEnv(t, Options{SSHConfigDir: dir})
		if err := env.service.EnsureIdentity("dsh-colin", env.remote.Workspace, env.remote.DshHome); err == nil {
			t.Fatal("a directory as a seed was accepted")
		}
	})
	t.Run("oversized", func(t *testing.T) {
		dir := writeSeed(t, "dsh-colin", strings.Repeat("# padding\n", 7000), 0o644)
		env := newTestEnv(t, Options{SSHConfigDir: dir})
		if err := env.service.EnsureIdentity("dsh-colin", env.remote.Workspace, env.remote.DshHome); err == nil {
			t.Fatal("an oversized seed was accepted")
		}
	})
}

// The requirement this feature exists for: the deployment account's own ~/.ssh/config is
// never a tenant's alias source. A decoy HOME makes that a property of the code rather than
// of the deployment file.
func TestTenantConfigNeverComesFromTheDeploymentAccountsSSHConfig(t *testing.T) {
	home := t.TempDir()
	if err := os.MkdirAll(filepath.Join(home, ".ssh"), 0o700); err != nil {
		t.Fatal(err)
	}
	decoy := "Host decoy\n  HostName 10.9.9.9\n  User operator\n"
	if err := os.WriteFile(filepath.Join(home, ".ssh", "config"), []byte(decoy), 0o600); err != nil {
		t.Fatal(err)
	}
	t.Setenv("HOME", home)

	env := newTestEnv(t, Options{})
	got := workspaceConfig(t, env.remote.Workspace)
	if strings.Contains(got, "decoy") || strings.Contains(got, "10.9.9.9") {
		t.Fatalf("the tenant config was seeded from the deployment account's ~/.ssh/config:\n%s", got)
	}
}

// The account owns its config once it exists: a later change to the seed (or none at all)
// must not resurrect or overwrite what the account has — that is where 「我的主机」lives.
func TestSeedChangesNeverOverwriteAnAccountsOwnConfig(t *testing.T) {
	dir := writeSeed(t, "dsh-colin", "Host seeded\n  HostName 10.0.0.1\n", 0o644)
	env := newTestEnv(t, Options{SSHConfigDir: dir})
	accountOwned := "Host mine\n  HostName 10.0.0.7\n"
	if err := os.WriteFile(filepath.Join(env.remote.Workspace, ".ssh", "config"), []byte(accountOwned), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "dsh-colin"), []byte("Host replaced\n  HostName 10.0.0.2\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := env.service.EnsureIdentity("dsh-colin", env.remote.Workspace, env.remote.DshHome); err != nil {
		t.Fatalf("EnsureIdentity: %v", err)
	}
	if got := workspaceConfig(t, env.remote.Workspace); got != accountOwned {
		t.Errorf("an account-owned config was rewritten: %q", got)
	}
}
