// Builds client.js from client.src.js.
//
// Why a build step at all: this installation ships no bundler, and dsh serves a client plugin's
// ./client file byte for byte as a classic same-origin script. This half vendors nothing — React
// comes from the shell's frozen module table and everything else is one RPC call — so "building"
// is stamping the source with the hashes of what was bundled into it, which is what makes the
// served bytes identifiable from the browser side.
//
// Run: node build-client.mjs   (writes ./client.js)

import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const read = (name) => readFileSync(join(here, name), 'utf8')
const digest = (text) => createHash('sha256').update(text).digest('hex').slice(0, 16)

const source = read('client.src.js')
const header = [
  '/* dshgw-workspace-files — generated by build-client.mjs; edit client.src.js, not this file.',
  ` * client.src.js                        sha256:${digest(source)}`,
  ' */',
  '',
].join('\n')

const output = `${header}${source}`
writeFileSync(join(here, 'client.js'), output)
const bytes = Buffer.byteLength(output)
process.stdout.write(`client.js written: ${bytes} bytes (${(bytes / 1024).toFixed(1)} KiB)\n`)
