#!/usr/bin/env bash
# Install aigw (+ its supervised dshgw child) as a user-level systemd service.
#
# Why a user unit rather than a system unit: M58's shape is rootless — aigw, the
# dshgw child it starts, and every tenant worker are the invoking account. A system
# unit would need root to install and would run under a different identity than the
# state directory's owner.
#
# Surviving a reboot needs the user manager to run without a login session
# (`loginctl enable-linger <user>`). Linger is a one-time root/polkit decision, so
# this script checks it and tells you the exact command instead of pretending a
# user unit alone is enough.
#
#   scripts/aigw_user_service.sh install [--config PATH] [--bin PATH] [--unit NAME] [--no-start]
#                                       [--memory-max BYTES] [--tasks-max N] [--cpu-quota PERCENT]
#   scripts/aigw_user_service.sh status
#   scripts/aigw_user_service.sh restart
#   scripts/aigw_user_service.sh uninstall
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
UNIT="${DSHGW_AIGW_UNIT:-aigw-local.service}"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
CONFIG="$ROOT/config.yaml"
BIN="$ROOT/bin/aigw"
LOG="$ROOT/data/aigw-local.log"
START=1
# Aggregate ceilings for the whole deployment (aigw + dshgw + every tenant worker).
# Empty means unlimited. Per-worker limits are configured in aigw's dshgw section
# and applied through each worker's own scope.
MEMORY_MAX=""
TASKS_MAX=""
CPU_QUOTA=""

usage() { sed -n '2,16p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    install|status|restart|uninstall) ACTION="$1"; shift ;;
    --config) CONFIG="$2"; shift 2 ;;
    --unit) UNIT="$2"; shift 2 ;;
    --bin) BIN="$2"; shift 2 ;;
    --no-start) START=0; shift ;;
    --memory-max) MEMORY_MAX="$2"; shift 2 ;;
    --tasks-max) TASKS_MAX="$2"; shift 2 ;;
    --cpu-quota) CPU_QUOTA="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done
ACTION="${ACTION:-status}"
# Computed after argument parsing: --unit must change where the file lands, not only
# which unit systemctl is asked about.
UNIT_PATH="$UNIT_DIR/$UNIT"

# config_endpoint reads "listen" and "base_path" out of the config and returns
# "<host:port> <base>", tolerant of quoting and of a listen value without a host
# ("":8088" binds every interface, so a probe must use loopback).
config_endpoint() {
  local cfg="$1" listen base
  listen="$(sed -n 's/^[[:space:]]*listen:[[:space:]]*//p' "$cfg" | head -1 | tr -d '\"' | tr -d "'" | tr -d ' ')"
  base="$(sed -n 's/^[[:space:]]*base_path:[[:space:]]*//p' "$cfg" | head -1 | tr -d '\"' | tr -d "'" | tr -d ' ')"
  if [[ "$listen" == :* ]]; then
    listen="127.0.0.1${listen}"
  fi
  printf '%s %s\n' "${listen:-127.0.0.1:8088}" "${base%/}"
}

# wait_ready polls the unit's own /healthz until it answers or the budget runs out.
#
# "systemctl restart returned" is not "the service is serving": aigw binds its port
# only after loading its registry and running bootstrap writes, which was measured at
# 34 seconds on this host's multi-gigabyte database. Reporting success before then
# hides an outage window in which every request (including DSH logins) fails.
wait_ready() {
  local url="$1" budget="${2:-60}" waited=0 code=""
  # (Callers pass a URL built from config values; those may arrive quoted.)
  while (( waited < budget )); do
    code="$(curl -s -o /dev/null -m 2 -w '%{http_code}' "$url" 2>/dev/null || true)"
    if [[ "$code" == "200" ]]; then
      printf 'ready after %ss (%s)\n' "$waited" "$url"
      return 0
    fi
    sleep 1
    waited=$((waited + 1))
  done
  echo "not ready after ${budget}s: last status ${code:-none} from $url" >&2
  return 1
}

require_user_manager() {
  if ! systemctl --user show-environment >/dev/null 2>&1; then
    echo "no systemd user manager for $(id -un); use 'bin/aigw --config ...' directly" >&2
    exit 1
  fi
}

linger_state() {
  loginctl show-user "$(id -un)" 2>/dev/null | sed -n 's/^Linger=//p' || true
}

write_unit() {
  [[ -f "$CONFIG" ]] || { echo "config not found: $CONFIG" >&2; exit 1; }
  [[ -x "$BIN" ]] || { echo "aigw binary not found or not executable: $BIN (run make build)" >&2; exit 1; }
  install -d -m 0700 "$UNIT_DIR" "$ROOT/data"
  UNIT_LIMITS=""
  [[ -n "$MEMORY_MAX" ]] && UNIT_LIMITS="$UNIT_LIMITS
MemoryMax=$MEMORY_MAX"
  [[ -n "$TASKS_MAX" ]] && UNIT_LIMITS="$UNIT_LIMITS
TasksMax=$TASKS_MAX"
  [[ -n "$CPU_QUOTA" ]] && UNIT_LIMITS="$UNIT_LIMITS
CPUQuota=$CPU_QUOTA%"
  cat >"$UNIT_PATH" <<UNIT
# Generated by scripts/aigw_user_service.sh — edit the script, not this file.
#
# aigw owns the DSH surface: it starts its sibling dshgw as a child and stops it on
# shutdown, so stopping this unit stops the tenants too.
[Unit]
Description=ai-gateway (aigw + supervised dshgw)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$ROOT
ExecStart=$BIN --config $CONFIG
Restart=on-failure
RestartSec=3
# The child and its tenant workers are in this unit's cgroup; a generous stop
# timeout lets dshgw take them down in order instead of being killed mid-shutdown.
KillMode=mixed
TimeoutStopSec=45
StandardOutput=append:$LOG
StandardError=append:$LOG$UNIT_LIMITS

[Install]
WantedBy=default.target
UNIT
  systemctl --user daemon-reload
  systemctl --user enable "$UNIT" >/dev/null
  echo "installed $UNIT_PATH"
}

case "$ACTION" in
  install)
    require_user_manager
    write_unit
    if [[ "$START" == 1 ]]; then
      systemctl --user restart "$UNIT"
      systemctl --user is-active "$UNIT" >/dev/null && echo "started $UNIT"
      # Read the port from the config so the gate matches the deployment.
      read -r listen base < <(config_endpoint "$CONFIG")
      wait_ready "http://${listen}${base}/healthz" 90 || {
        echo "warning: $UNIT is active but not answering yet; check the log" >&2
        exit 1
      }
    fi
    if [[ "$(linger_state)" != "yes" ]]; then
      cat >&2 <<EOF
warning: linger is off for $(id -un), so this unit starts only while you are logged in.
         enable it once (needs root/polkit):
             sudo loginctl enable-linger $(id -un)
EOF
    else
      echo "linger is on: the unit starts at boot without a login session"
    fi
    ;;
  status)
    require_user_manager
    systemctl --user --no-pager status "$UNIT" 2>&1 | head -12 || true
    printf 'enabled: %s  linger: %s\n' "$(systemctl --user is-enabled "$UNIT" 2>/dev/null || echo no)" "$(linger_state)"
    ;;
  restart)
    require_user_manager
    systemctl --user restart "$UNIT"
    echo "restarted $UNIT"
    read -r listen base < <(config_endpoint "$CONFIG")
    wait_ready "http://${listen}${base}/healthz" 90
    ;;
  uninstall)
    require_user_manager
    systemctl --user disable --now "$UNIT" >/dev/null 2>&1 || true
    rm -f "$UNIT_PATH"
    systemctl --user daemon-reload
    echo "removed $UNIT_PATH"
    ;;
esac
