#!/usr/bin/env bash
# Install aigw (+ its supervised dshgw child) as a user-level systemd service.
#
# Why a user unit rather than a system unit: M58's shape is rootless — aigw, the
# dshgw child it starts, and every tenant worker are the invoking account. A system
# unit would need root to install and would run under a different identity than the
# state directory's owner.
#
# Surviving a reboot needs the user manager to run without a login session
# (`loginctl enable-linger <user>`). Linger is a one-time root/polkit decision, so
# this script checks it and tells you the exact command instead of pretending a
# user unit alone is enough.
#
#   scripts/aigw_user_service.sh install [--config PATH] [--bin PATH] [--unit NAME] [--no-start]
#   scripts/aigw_user_service.sh status
#   scripts/aigw_user_service.sh restart
#   scripts/aigw_user_service.sh uninstall
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
UNIT="${DSHGW_AIGW_UNIT:-aigw-local.service}"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
CONFIG="$ROOT/config.yaml"
BIN="$ROOT/bin/aigw"
LOG="$ROOT/data/aigw-local.log"
START=1

usage() { sed -n '2,16p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    install|status|restart|uninstall) ACTION="$1"; shift ;;
    --config) CONFIG="$2"; shift 2 ;;
    --unit) UNIT="$2"; shift 2 ;;
    --bin) BIN="$2"; shift 2 ;;
    --no-start) START=0; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done
ACTION="${ACTION:-status}"
# Computed after argument parsing: --unit must change where the file lands, not only
# which unit systemctl is asked about.
UNIT_PATH="$UNIT_DIR/$UNIT"

require_user_manager() {
  if ! systemctl --user show-environment >/dev/null 2>&1; then
    echo "no systemd user manager for $(id -un); use 'bin/aigw --config ...' directly" >&2
    exit 1
  fi
}

linger_state() {
  loginctl show-user "$(id -un)" 2>/dev/null | sed -n 's/^Linger=//p' || true
}

write_unit() {
  [[ -f "$CONFIG" ]] || { echo "config not found: $CONFIG" >&2; exit 1; }
  [[ -x "$BIN" ]] || { echo "aigw binary not found or not executable: $BIN (run make build)" >&2; exit 1; }
  install -d -m 0700 "$UNIT_DIR" "$ROOT/data"
  cat >"$UNIT_PATH" <<UNIT
# Generated by scripts/aigw_user_service.sh — edit the script, not this file.
#
# aigw owns the DSH surface: it starts its sibling dshgw as a child and stops it on
# shutdown, so stopping this unit stops the tenants too.
[Unit]
Description=ai-gateway (aigw + supervised dshgw)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$ROOT
ExecStart=$BIN --config $CONFIG
Restart=on-failure
RestartSec=3
# The child and its tenant workers are in this unit's cgroup; a generous stop
# timeout lets dshgw take them down in order instead of being killed mid-shutdown.
KillMode=mixed
TimeoutStopSec=45
StandardOutput=append:$LOG
StandardError=append:$LOG

[Install]
WantedBy=default.target
UNIT
  systemctl --user daemon-reload
  systemctl --user enable "$UNIT" >/dev/null
  echo "installed $UNIT_PATH"
}

case "$ACTION" in
  install)
    require_user_manager
    write_unit
    if [[ "$START" == 1 ]]; then
      systemctl --user restart "$UNIT"
      sleep 2
      systemctl --user is-active "$UNIT" >/dev/null && echo "started $UNIT"
    fi
    if [[ "$(linger_state)" != "yes" ]]; then
      cat >&2 <<EOF
warning: linger is off for $(id -un), so this unit starts only while you are logged in.
         enable it once (needs root/polkit):
             sudo loginctl enable-linger $(id -un)
EOF
    else
      echo "linger is on: the unit starts at boot without a login session"
    fi
    ;;
  status)
    require_user_manager
    systemctl --user --no-pager status "$UNIT" 2>&1 | head -12 || true
    printf 'enabled: %s  linger: %s\n' "$(systemctl --user is-enabled "$UNIT" 2>/dev/null || echo no)" "$(linger_state)"
    ;;
  restart)
    require_user_manager
    systemctl --user restart "$UNIT"
    echo "restarted $UNIT"
    ;;
  uninstall)
    require_user_manager
    systemctl --user disable --now "$UNIT" >/dev/null 2>&1 || true
    rm -f "$UNIT_PATH"
    systemctl --user daemon-reload
    echo "removed $UNIT_PATH"
    ;;
esac
