// Package pinyin answers "how is this character read" for the one thing the gateway needs it for:
// naming a dsh tenant after the account it belongs to (M74).
//
// The table is generated by scripts/gen-pinyin.py and is the *same* table the console filters with
// (internal/webui/static/js/pinyin.js) — same source file, same SHA-256, same record order — because
// a name an operator sees in a pre-filled dialog and the name the gateway writes when nobody is
// looking have to agree. internal/pinyin/pinyin_test.go asserts the two blobs are byte-identical.
//
// Why two files instead of reading one: the console is a zero-build ES module tree that can only
// import assets under internal/webui/static, and a release build replaces those assets with a
// minified mirror (`make build` → go build -overlay, see docs/design/m50-frontend-minify.md), so the
// Go side cannot read the table back out of the artifact it ships.
package pinyin

import (
	"strings"
	"sync"
)

// rangeStart is the first codepoint of the generated table (CJK Unified Ideographs).
const rangeStart = 0x4E00

// FirstReading returns the first, tone-stripped reading of one character ("chen" for 陈, "nu" for
// 女 — the generator removes the diacritics with NFD, so ü loses its umlaut rather than becoming v),
// or "" when the table has no reading for it: a non-CJK character, or an ideograph outside the
// covered block.
//
// The *first* reading is the deterministic choice for a name. A character like 长 is both chang and
// zhang, and the console's filter deliberately enumerates all of them, but a tenant name is written
// once and then read by people forever, so it has to be reproducible rather than exhaustive.
func FirstReading(r rune) string {
	rows := readings()
	index := int(r) - rangeStart
	if index < 0 || index >= len(rows) {
		return ""
	}
	row := rows[index]
	if cut := strings.IndexByte(row, ','); cut >= 0 {
		row = row[:cut]
	}
	return row
}

var (
	tableOnce sync.Once
	table     []string
)

// readings splits the generated blob on first use. Nothing on a request path reaches it unless an
// account actually needs a name, so a deployment that never enables dsh never pays the 20992
// splits (the console makes the same trade-off with its own lazy table).
func readings() []string {
	tableOnce.Do(func() { table = strings.Split(readingsBlob, "\n") })
	return table
}
